title: Planter
remote_theme: pmarsceill/just-the-docs
logo: "/images/icon_and_logo_no_shadow.svg"
# Aux links for the upper right navigation
#aux_links:
#  "Web App":
#    - "http://gardenplanter.app"