title: Planter
remote_theme: pmarsceill/just-the-docs
logo: "/images/icon_and_logo_no_shadow.svg"
# Aux links for the upper right navigation
#aux_links:
#  "Web App":
#    - "http://gardenplanter.app"
color_scheme: planter

# Search
search_enabled: true

# Split pages into sections that can be searched individually
# Supports 1 - 6, default: 2
search.heading_level: 2

# Maximum amount of previews per search result
# Default: 3
search.previews: 3

# Maximum amount of words to display before a matched word in the preview
# Default: 5
search.preview_words_before: 5

# Maximum amount of words to display after a matched word in the preview
# Default: 10
search.preview_words_after: 10

# Enable or disable the search button that appears in the bottom right corner of every page
# Supports true or false (default)
search.button: true

# Set the search token separator
# Default: /[\s\-/]+/
# Example: enable support for hyphenated search words
search.tokenizer_separator: /[\s/]+/